### ISSUE TITLE
Usernames

### ISSUE THREAD

**Issue by devskar** [layla-oskar-schule/vinopinions-api#139]
Questions:
1. Should usernames be able to consist only of number e.g. '1231'
2. Should usernames be able to consist only of special characters e.g. '____'

Whats the way here?

**Comment by tschokri** [comment]
i think users shouldn't be allowed to pick names only consisting of numbers and/or special characters

**Comment by devskar** [comment]
Allowed:
- hans
- hans123
- h123ans
- hans_123
- hans_

Not allowed:
- _hans
- 123hans
- hans__
